
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount your local code into the container for hot-reloading
      - .:/app
    environment:
      - ENVIRONMENT=development
    # Override the CMD to enable auto-reload for development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 